# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Bring up kafka environemnt
      uses: isbang/compose-action@v0.1
      with:
        compose-file: 'docker/docker-compose.yaml'
    - name: Install Kafka CLI
      run: |
        echo "A initial message"
        mkdir ~/kafka && cd ~/kafka
        curl -o kafka.tgz https://apache.mirror.digitalpacific.com.au/kafka/2.7.0/kafka_2.13-2.7.0.tgz
        tar -xvzf kafka.tgz --strip 1  
    - name: Test
      run: |
        docker ps
        pwd
        cd ~/kafka/bin
        pwd
        ls -l
        kafka-topics.sh --bootstrap-server localhost:29092 --list
        kafka-topics.sh --bootstrap-server localhost:29092 --delete --topic users
        kafka-topics.sh --bootstrap-server localhost:29092 --create --topic users --partitions 3 --replication-factor 1
        kafka-topics.sh --bootstrap-server localhost:29092 --list